# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0c0a8062f4342abfb6e1fcb9e9d22effdaafb5ee044ef28da32854a3e80fb455cc92ce96aef60fbfbf2e0ca9cf6581fa9172baf38d8f979783c09b901553769

test:
  secret_key_base: ff349b03424ed93d669de289136b9b70b6a4885853d8dc4a205fbb007c74df8a418d07c972db71e2525410a3a4219acfdcab99d8d1ed3c46b3067b2060e465ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
